[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "pytrove"
dynamic = ["version"]
description = "Python Tools library for some services"
requires-python = ">=3.10"
authors = [{ name = "Abdullah", email = "aldheeb01@gmail.com" }]
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

dependencies = [
    "typing_extensions>=4.0; python_version<'3.13'",
]


[project.urls]
"Homepage" = "https://github.com/eeeob/pytrove"

[project.optional-dependencies]
dev = [
    "hatch<=1.16.5",
    "twine<=6.2.0",
    "pytest>=8",
    "pytest-asyncio>=0.24",
]


mongo = ["pymongo>=4.6.3"]
country = ["pycountry>=26.2.16", "phonenumbers>=9.0.21"]
crypto = ["cryptography>=48.0.1"]
bs4 = ["beautifulsoup4>=4.14.3"]
imap = ["aioimaplib>=2.0.1"]
phone = ["phonenumbers>=9.0.21"]
tg = ["kurigram>=2.1.35"]
typecheck = ["typeguard>=4.3"]
proxy = ["wrapt>=1.16"]
locale = ["babel>=2.14"]
jsonref = ["jsonref>=1.1"]
fastjson = ["orjson>=3.9"]
archive = [
    "zstandard>=0.22; python_version < '3.14'",
    "fastzip>=0.5",
    "pathspec>=1.0",
]

full = [
    "pytrove[imap,phone,country,bs4,mongo,tg,crypto,typecheck,proxy,locale,jsonref,fastjson,archive]"
]

[tool.hatch.build.targets.sdist]
exclude = [".github/",]

[tool.hatch.version]
path = "pytrove/__meta__.py"


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["pytrove"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"